context:
  version: "0.23.6"

package:
  name: zola
  version: ${{ version }}

source:
  url: https://github.com/getzola/zola/archive/v${{ version }}.tar.gz
  sha256: 193db594222cd9c1097387ce17272cbbe672c3a894c263f6f4c436a7fedb379f

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - pkg-config
  host:
    - oniguruma

tests:
  - script:
      - zola --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: A fast static site generator in a single binary with everything built-in.
  homepage: https://github.com/getzola/zola
  repository: https://github.com/getzola/zola

extra:
  recipe-maintainers:
    - danielnachun
